version: '3.1'
services:
  stats-server:
    ports:
      - "9090:9090"
    build: stats/stats-service
    container_name:
      stats-server
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat_db
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat_pass
  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name:
      stats-service-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat_pass
  ewm-service:
    ports:
      - "8080:8080"
    build: ewm-service
    container_name:
      ewm-server
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_db
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=ewm_pass
      - STATS_CLIENT_URL=http://stats-server:9090
  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name:
      ewm-service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=ewm_pass