CREATE TABLE IF NOT EXISTS hits
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app character varying,
    uri character varying,
    ip character varying,
    "timestamp" timestamp without time zone,
    CONSTRAINT pk_hit PRIMARY KEY (id)
);